# SPDX-FileCopyrightText: 2026 Iva Horn
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
    "**/*.xml", 
    "**/*.png", 
    "**/*.pxd",
    "**/*.json",
    "AGENTS.md",
    "Package.resolved",
    ".gitignore", 
    ".swiftformat", 
    ".swift-version", 
    "README.md",
    "Sources/Rivers/Documentation.docc/**/*",
    "Tests/RiversTests/Responses/**"
]
SPDX-FileCopyrightText = "2026 Iva Horn"
SPDX-License-Identifier = "MIT"
