// SPDX-FileCopyrightText: 2026 Iva Horn
// SPDX-License-Identifier: MIT

import Foundation

///
/// Configuration for `FileJournal`. Controls where log files are written, how the current journal lifetime ("session") is named on disk, and how large the active file may grow before being rotated.
///
public struct FileJournalConfiguration: Sendable {
    ///
    /// File-name extension applied to the on-disk parent directory so macOS treats it as an opaque package (analogous to `.numbers`, `.imovielibrary`, etc.) and Finder opens it as a single document in a reader app that declares the matching UTI.
    ///
    public static let directoryExtension = "rivers"

    ///
    /// The parent directory containing one subdirectory per `FileJournal` lifetime. Created on demand if it does not exist.
    ///
    /// Presented to Finder as a macOS package and therefore always carries the `.\(directoryExtension)` extension on disk. `init` augments — never replaces — the extension of the URL it receives, so a caller-supplied `Logs/MyApp.log` becomes `Logs/MyApp.log.rivers`.
    ///
    public let directory: URL

    ///
    /// Identifier of this journal session. Generated by `init` from the current ISO8601 timestamp combined with a short random suffix so that successive journal lifetimes produce distinct, chronologically-sortable folder names. Used as the name of the subdirectory inside `directory` into which all of the journal's files are written.
    ///
    public let sessionID: String

    ///
    /// The size threshold in bytes at which the active log file is rotated and compressed.
    ///
    public let maxFileBytes: Int

    ///
    /// Create a configuration. Defaults to a 5 MiB rotation threshold.
    ///
    /// `directory` is normalized so its `pathExtension` is `\(directoryExtension)`; the extension is appended if missing and left alone if already present.
    ///
    public init(directory: URL, maxFileBytes: Int = 5 * 1024 * 1024) {
        self.directory = Self.normalize(directory)
        sessionID = Self.makeIdentifier()
        self.maxFileBytes = maxFileBytes
    }

    static func normalize(_ directory: URL) -> URL {
        if directory.pathExtension == directoryExtension {
            return directory
        }

        return directory.appendingPathExtension(directoryExtension)
    }

    static func makeIdentifier() -> String {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]

        let timestamp = formatter.string(from: Date()).replacingOccurrences(of: ":", with: "-")
        let suffix = String(UUID().uuidString.replacingOccurrences(of: "-", with: "").prefix(8))

        return "\(timestamp)-\(suffix)"
    }
}
